name: release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        required: false
        type: boolean
        default: false
        description: "Prerelease"

jobs:
  prepare:
    runs-on: ubuntu-latest
   
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main
    - name: Create bump and changelog
      uses: commitizen-tools/commitizen-action@master
      with:
        git_name: ${{ github.actor }}
        git_email: ${{ github.actor }}@users.noreply.github.com
        push: "false"
        prerelease: ${{ github.event.inputs.prerelease }}
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        changelog_increment_filename: body.md 
    - name: Craft details
      run: |
        echo "change=$(cat body.md)" >> $GITHUB_ENV
        echo "title=$(git show -s --format=%s)" >> $GITHUB_ENV
        rm body.md
        git status
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: release
        delete-branch: true
        base: main
        title: ${{ env.title }}
        body: ${{ env.body }}
